version: "3"
services:
    # app:
    #     build: .
    #     ports:
    #         - "3000:3000"
    #     volumes:
    #         - .:/usr/app
    #         - /usr/app/node_modules
    #     command: yarn dev
    db:
        image: postgres:11.2-alpine
        container_name: "selecao-globo-db"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: adpost
            POSTGRES_PASSWORD: adpost
            POSTGRES_DB: selecao-globo